services:
  talks-service:
    container_name: talks-service
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data: